/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ticketing Platform API
 * OpenAPI spec version: 0.1
 */
import * as zod from 'zod';


export const AppControllerGetDataResponse = zod.unknown()

