/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ticketing Platform API
 * OpenAPI spec version: 0.1
 */
import * as zod from 'zod';


export const authControllerRegisterBodyPasswordMin = 8;



export const AuthControllerRegisterBody = zod.object({
  "email": zod.email(),
  "password": zod.string().min(authControllerRegisterBodyPasswordMin),
  "role": zod.enum(['attendee', 'organizer'])
})

export const AuthControllerRegisterResponse = zod.object({
  "accessToken": zod.string(),
  "user": zod.object({
  "id": zod.string(),
  "email": zod.string(),
  "role": zod.enum(['attendee', 'organizer', 'admin'])
})
})

export const authControllerLoginBodyPasswordMin = 8;



export const AuthControllerLoginBody = zod.object({
  "email": zod.email(),
  "password": zod.string().min(authControllerLoginBodyPasswordMin)
})

export const AuthControllerLoginResponse = zod.object({
  "accessToken": zod.string(),
  "user": zod.object({
  "id": zod.string(),
  "email": zod.string(),
  "role": zod.enum(['attendee', 'organizer', 'admin'])
})
})

export const AuthControllerRefreshResponse = zod.object({
  "accessToken": zod.string()
})

export const AuthControllerLogoutResponse = zod.void()

export const AuthControllerMeResponse = zod.object({
  "id": zod.string(),
  "email": zod.string(),
  "role": zod.enum(['attendee', 'organizer', 'admin'])
})

