/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ticketing Platform API
 * OpenAPI spec version: 0.1
 */
import * as zod from 'zod';


export const EventsControllerListEventsResponseItem = zod.object({
  "id": zod.string(),
  "venueId": zod.string(),
  "title": zod.string(),
  "startsAt": zod.iso.datetime({"offset":true}),
  "posterUrl": zod.string().nullable()
})
export const EventsControllerListEventsResponse = zod.array(EventsControllerListEventsResponseItem)

export const EventsControllerCreateBody = zod.object({
  "venueId": zod.string(),
  "title": zod.string(),
  "startsAt": zod.string()
})

export const EventsControllerCreateResponse = zod.object({
  "id": zod.string(),
  "venueId": zod.string(),
  "title": zod.string(),
  "startsAt": zod.iso.datetime({"offset":true}),
  "posterUrl": zod.string().nullable()
})

export const EventsControllerGetEventParams = zod.object({
  "id": zod.string()
})

export const EventsControllerGetEventResponse = zod.object({
  "id": zod.string(),
  "venueId": zod.string(),
  "title": zod.string(),
  "startsAt": zod.iso.datetime({"offset":true}),
  "posterUrl": zod.string().nullable()
})

export const EventsControllerUpdateParams = zod.object({
  "id": zod.string()
})

export const EventsControllerUpdateBody = zod.object({
  "title": zod.string().optional(),
  "startsAt": zod.string().optional()
})

export const EventsControllerUpdateResponse = zod.object({
  "id": zod.string(),
  "venueId": zod.string(),
  "title": zod.string(),
  "startsAt": zod.iso.datetime({"offset":true}),
  "posterUrl": zod.string().nullable()
})

export const EventsControllerGetSeatsParams = zod.object({
  "id": zod.string()
})

export const EventsControllerGetSeatsResponseItem = zod.object({
  "id": zod.string(),
  "eventId": zod.string(),
  "label": zod.string(),
  "status": zod.enum(['available', 'held', 'booked']),
  "price": zod.number()
})
export const EventsControllerGetSeatsResponse = zod.array(EventsControllerGetSeatsResponseItem)

export const EventsControllerUploadPosterParams = zod.object({
  "id": zod.string()
})

export const EventsControllerUploadPosterBody = zod.object({
  "file": zod.instanceof(Blob).optional()
})

export const EventsControllerUploadPosterResponse = zod.object({
  "id": zod.string(),
  "venueId": zod.string(),
  "title": zod.string(),
  "startsAt": zod.iso.datetime({"offset":true}),
  "posterUrl": zod.string().nullable()
})

