/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ticketing Platform API
 * OpenAPI spec version: 0.1
 */
import type { UserDto } from './userDto.js';

export interface AuthResponseDto {
  accessToken: string;
  user: UserDto;
}
