/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ticketing Platform API
 * OpenAPI spec version: 0.1
 */

export interface CreateEventDto {
  venueId: string;
  title: string;
  startsAt: string;
}
