/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ticketing Platform API
 * OpenAPI spec version: 0.1
 */

/**
 * @nullable
 */
export type EventDtoPosterUrl = { [key: string]: unknown } | null;
