/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ticketing Platform API
 * OpenAPI spec version: 0.1
 */

export interface EventDto {
  id: string;
  venueId: string;
  title: string;
  startsAt: string;
  /** @nullable */
  posterUrl: string | null;
}
