/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ticketing Platform API
 * OpenAPI spec version: 0.1
 */
import type { EventDtoPosterUrl } from './eventDtoPosterUrl.js';

export interface EventDto {
  id: string;
  venueId: string;
  title: string;
  startsAt: string;
  /** @nullable */
  posterUrl: EventDtoPosterUrl;
}
