/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ticketing Platform API
 * OpenAPI spec version: 0.1
 */

export type RegisterDtoRole = typeof RegisterDtoRole[keyof typeof RegisterDtoRole];


export const RegisterDtoRole = {
  attendee: 'attendee',
  organizer: 'organizer',
} as const;
