/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ticketing Platform API
 * OpenAPI spec version: 0.1
 */
import type { RegisterDtoRole } from './registerDtoRole.js';

export interface RegisterDto {
  email: string;
  /** @minLength 8 */
  password: string;
  role: RegisterDtoRole;
}
