/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ticketing Platform API
 * OpenAPI spec version: 0.1
 */

export type SeatDtoStatus = typeof SeatDtoStatus[keyof typeof SeatDtoStatus];


export const SeatDtoStatus = {
  available: 'available',
  held: 'held',
  booked: 'booked',
} as const;
