/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ticketing Platform API
 * OpenAPI spec version: 0.1
 */
import type { SeatDtoStatus } from './seatDtoStatus.js';

export interface SeatDto {
  id: string;
  eventId: string;
  label: string;
  status: SeatDtoStatus;
  price: number;
}
