/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ticketing Platform API
 * OpenAPI spec version: 0.1
 */
import type { UserDtoRole } from './userDtoRole.js';

export interface UserDto {
  id: string;
  email: string;
  role: UserDtoRole;
}
