/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ticketing Platform API
 * OpenAPI spec version: 0.1
 */

export type UserDtoRole = typeof UserDtoRole[keyof typeof UserDtoRole];


export const UserDtoRole = {
  attendee: 'attendee',
  organizer: 'organizer',
  admin: 'admin',
} as const;
