/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ticketing Platform API
 * OpenAPI spec version: 0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateEventDto,
  EventDto,
  EventsControllerListEventsParams,
  EventsControllerUploadPosterBody,
  SeatDto,
  UpdateEventDto
} from '../../models';

import { customInstance } from '../../mutator.js';




const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const eventsControllerListEvents = (
    params?: EventsControllerListEventsParams,
 signal?: AbortSignal
) => {


      return customInstance<EventDto[]>(
      {url: `/api/events`, method: 'GET',
        params, signal
    },
      );
    }




export const getEventsControllerListEventsQueryKey = (params?: EventsControllerListEventsParams,) => {
    return [
    `/api/events`, ...(params ? [params] : [])
    ] as const;
    }


export const getEventsControllerListEventsQueryOptions = <TData = Awaited<ReturnType<typeof eventsControllerListEvents>>, TError = unknown>(params?: EventsControllerListEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventsControllerListEvents>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEventsControllerListEventsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof eventsControllerListEvents>>> = ({ signal }) => eventsControllerListEvents(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof eventsControllerListEvents>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EventsControllerListEventsQueryResult = NonNullable<Awaited<ReturnType<typeof eventsControllerListEvents>>>
export type EventsControllerListEventsQueryError = unknown


export function useEventsControllerListEvents<TData = Awaited<ReturnType<typeof eventsControllerListEvents>>, TError = unknown>(
 params: undefined |  EventsControllerListEventsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventsControllerListEvents>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventsControllerListEvents>>,
          TError,
          Awaited<ReturnType<typeof eventsControllerListEvents>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEventsControllerListEvents<TData = Awaited<ReturnType<typeof eventsControllerListEvents>>, TError = unknown>(
 params?: EventsControllerListEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventsControllerListEvents>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventsControllerListEvents>>,
          TError,
          Awaited<ReturnType<typeof eventsControllerListEvents>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEventsControllerListEvents<TData = Awaited<ReturnType<typeof eventsControllerListEvents>>, TError = unknown>(
 params?: EventsControllerListEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventsControllerListEvents>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useEventsControllerListEvents<TData = Awaited<ReturnType<typeof eventsControllerListEvents>>, TError = unknown>(
 params?: EventsControllerListEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventsControllerListEvents>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEventsControllerListEventsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const eventsControllerCreate = (
    createEventDto: CreateEventDto,
 signal?: AbortSignal
) => {


      return customInstance<EventDto>(
      {url: `/api/events`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createEventDto, signal
    },
      );
    }




export const getEventsControllerCreateMutationKey = () => ['eventsControllerCreate'] as const;

export const getEventsControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventsControllerCreate>>, TError,EventsControllerCreateMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof eventsControllerCreate>>, TError,EventsControllerCreateMutationVariables, TContext> => {

const mutationKey = getEventsControllerCreateMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof eventsControllerCreate>>, EventsControllerCreateMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  eventsControllerCreate(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EventsControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof eventsControllerCreate>>>
    export type EventsControllerCreateMutationBody = CreateEventDto
    export type EventsControllerCreateMutationError = unknown
    export type EventsControllerCreateMutationVariables = {data: CreateEventDto}

    export const useEventsControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventsControllerCreate>>, TError,EventsControllerCreateMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof eventsControllerCreate>>,
        TError,
        EventsControllerCreateMutationVariables,
        TContext
      > => {
      return useMutation(getEventsControllerCreateMutationOptions(options), queryClient);
    }
    export const eventsControllerGetEvent = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<EventDto>(
      {url: `/api/events/${id}`, method: 'GET', signal
    },
      );
    }




export const getEventsControllerGetEventQueryKey = (id: string,) => {
    return [
    `/api/events/${id}`
    ] as const;
    }


export const getEventsControllerGetEventQueryOptions = <TData = Awaited<ReturnType<typeof eventsControllerGetEvent>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventsControllerGetEvent>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEventsControllerGetEventQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof eventsControllerGetEvent>>> = ({ signal }) => eventsControllerGetEvent(id, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof eventsControllerGetEvent>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EventsControllerGetEventQueryResult = NonNullable<Awaited<ReturnType<typeof eventsControllerGetEvent>>>
export type EventsControllerGetEventQueryError = unknown


export function useEventsControllerGetEvent<TData = Awaited<ReturnType<typeof eventsControllerGetEvent>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventsControllerGetEvent>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventsControllerGetEvent>>,
          TError,
          Awaited<ReturnType<typeof eventsControllerGetEvent>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEventsControllerGetEvent<TData = Awaited<ReturnType<typeof eventsControllerGetEvent>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventsControllerGetEvent>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventsControllerGetEvent>>,
          TError,
          Awaited<ReturnType<typeof eventsControllerGetEvent>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEventsControllerGetEvent<TData = Awaited<ReturnType<typeof eventsControllerGetEvent>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventsControllerGetEvent>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useEventsControllerGetEvent<TData = Awaited<ReturnType<typeof eventsControllerGetEvent>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventsControllerGetEvent>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEventsControllerGetEventQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const eventsControllerUpdate = (
    id: string,
    updateEventDto: UpdateEventDto,
 signal?: AbortSignal
) => {


      return customInstance<EventDto>(
      {url: `/api/events/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateEventDto, signal
    },
      );
    }




export const getEventsControllerUpdateMutationKey = () => ['eventsControllerUpdate'] as const;

export const getEventsControllerUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventsControllerUpdate>>, TError,EventsControllerUpdateMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof eventsControllerUpdate>>, TError,EventsControllerUpdateMutationVariables, TContext> => {

const mutationKey = getEventsControllerUpdateMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof eventsControllerUpdate>>, EventsControllerUpdateMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  eventsControllerUpdate(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EventsControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof eventsControllerUpdate>>>
    export type EventsControllerUpdateMutationBody = UpdateEventDto
    export type EventsControllerUpdateMutationError = unknown
    export type EventsControllerUpdateMutationVariables = {id: string;data: UpdateEventDto}

    export const useEventsControllerUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventsControllerUpdate>>, TError,EventsControllerUpdateMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof eventsControllerUpdate>>,
        TError,
        EventsControllerUpdateMutationVariables,
        TContext
      > => {
      return useMutation(getEventsControllerUpdateMutationOptions(options), queryClient);
    }
    export const eventsControllerGetSeats = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<SeatDto[]>(
      {url: `/api/events/${id}/seats`, method: 'GET', signal
    },
      );
    }




export const getEventsControllerGetSeatsQueryKey = (id: string,) => {
    return [
    `/api/events/${id}/seats`
    ] as const;
    }


export const getEventsControllerGetSeatsQueryOptions = <TData = Awaited<ReturnType<typeof eventsControllerGetSeats>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventsControllerGetSeats>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEventsControllerGetSeatsQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof eventsControllerGetSeats>>> = ({ signal }) => eventsControllerGetSeats(id, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof eventsControllerGetSeats>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EventsControllerGetSeatsQueryResult = NonNullable<Awaited<ReturnType<typeof eventsControllerGetSeats>>>
export type EventsControllerGetSeatsQueryError = unknown


export function useEventsControllerGetSeats<TData = Awaited<ReturnType<typeof eventsControllerGetSeats>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventsControllerGetSeats>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventsControllerGetSeats>>,
          TError,
          Awaited<ReturnType<typeof eventsControllerGetSeats>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEventsControllerGetSeats<TData = Awaited<ReturnType<typeof eventsControllerGetSeats>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventsControllerGetSeats>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventsControllerGetSeats>>,
          TError,
          Awaited<ReturnType<typeof eventsControllerGetSeats>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEventsControllerGetSeats<TData = Awaited<ReturnType<typeof eventsControllerGetSeats>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventsControllerGetSeats>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useEventsControllerGetSeats<TData = Awaited<ReturnType<typeof eventsControllerGetSeats>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventsControllerGetSeats>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEventsControllerGetSeatsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const eventsControllerUploadPoster = (
    id: string,
    eventsControllerUploadPosterBody: EventsControllerUploadPosterBody,
 signal?: AbortSignal
) => {

      const formData = new FormData();
if(eventsControllerUploadPosterBody.file !== undefined) {
 formData.append(`file`, eventsControllerUploadPosterBody.file);
 }

      return customInstance<EventDto>(
      {url: `/api/events/${id}/poster`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData, signal
    },
      );
    }




export const getEventsControllerUploadPosterMutationKey = () => ['eventsControllerUploadPoster'] as const;

export const getEventsControllerUploadPosterMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventsControllerUploadPoster>>, TError,EventsControllerUploadPosterMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof eventsControllerUploadPoster>>, TError,EventsControllerUploadPosterMutationVariables, TContext> => {

const mutationKey = getEventsControllerUploadPosterMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof eventsControllerUploadPoster>>, EventsControllerUploadPosterMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  eventsControllerUploadPoster(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EventsControllerUploadPosterMutationResult = NonNullable<Awaited<ReturnType<typeof eventsControllerUploadPoster>>>
    export type EventsControllerUploadPosterMutationBody = EventsControllerUploadPosterBody
    export type EventsControllerUploadPosterMutationError = unknown
    export type EventsControllerUploadPosterMutationVariables = {id: string;data: EventsControllerUploadPosterBody}

    export const useEventsControllerUploadPoster = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventsControllerUploadPoster>>, TError,EventsControllerUploadPosterMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof eventsControllerUploadPoster>>,
        TError,
        EventsControllerUploadPosterMutationVariables,
        TContext
      > => {
      return useMutation(getEventsControllerUploadPosterMutationOptions(options), queryClient);
    }
