/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ticketing Platform API
 * OpenAPI spec version: 0.1
 */
import * as zod from 'zod';


export const VenuesControllerCreateBody = zod.object({
  "name": zod.string(),
  "address": zod.string()
})

export const VenuesControllerCreateResponse = zod.object({
  "id": zod.string(),
  "organizerId": zod.string(),
  "name": zod.string(),
  "address": zod.string()
})

export const VenuesControllerFindMineResponseItem = zod.object({
  "id": zod.string(),
  "organizerId": zod.string(),
  "name": zod.string(),
  "address": zod.string()
})
export const VenuesControllerFindMineResponse = zod.array(VenuesControllerFindMineResponseItem)

export const VenuesControllerFindOneParams = zod.object({
  "id": zod.string()
})

export const VenuesControllerFindOneResponse = zod.object({
  "id": zod.string(),
  "organizerId": zod.string(),
  "name": zod.string(),
  "address": zod.string()
})

export const VenuesControllerUpdateParams = zod.object({
  "id": zod.string()
})

export const VenuesControllerUpdateBody = zod.object({
  "name": zod.string().optional(),
  "address": zod.string().optional()
})

export const VenuesControllerUpdateResponse = zod.object({
  "id": zod.string(),
  "organizerId": zod.string(),
  "name": zod.string(),
  "address": zod.string()
})

