/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ticketing Platform API
 * OpenAPI spec version: 0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateVenueDto,
  UpdateVenueDto,
  VenueDto
} from '../../models';

import { customInstance } from '../../mutator.js';




const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const venuesControllerCreate = (
    createVenueDto: CreateVenueDto,
 signal?: AbortSignal
) => {


      return customInstance<VenueDto>(
      {url: `/api/venues`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createVenueDto, signal
    },
      );
    }




export const getVenuesControllerCreateMutationKey = () => ['venuesControllerCreate'] as const;

export const getVenuesControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof venuesControllerCreate>>, TError,VenuesControllerCreateMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof venuesControllerCreate>>, TError,VenuesControllerCreateMutationVariables, TContext> => {

const mutationKey = getVenuesControllerCreateMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof venuesControllerCreate>>, VenuesControllerCreateMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  venuesControllerCreate(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type VenuesControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof venuesControllerCreate>>>
    export type VenuesControllerCreateMutationBody = CreateVenueDto
    export type VenuesControllerCreateMutationError = unknown
    export type VenuesControllerCreateMutationVariables = {data: CreateVenueDto}

    export const useVenuesControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof venuesControllerCreate>>, TError,VenuesControllerCreateMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof venuesControllerCreate>>,
        TError,
        VenuesControllerCreateMutationVariables,
        TContext
      > => {
      return useMutation(getVenuesControllerCreateMutationOptions(options), queryClient);
    }
    export const venuesControllerFindMine = (

 signal?: AbortSignal
) => {


      return customInstance<VenueDto[]>(
      {url: `/api/venues`, method: 'GET', signal
    },
      );
    }




export const getVenuesControllerFindMineQueryKey = () => {
    return [
    `/api/venues`
    ] as const;
    }


export const getVenuesControllerFindMineQueryOptions = <TData = Awaited<ReturnType<typeof venuesControllerFindMine>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof venuesControllerFindMine>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getVenuesControllerFindMineQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof venuesControllerFindMine>>> = ({ signal }) => venuesControllerFindMine(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof venuesControllerFindMine>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type VenuesControllerFindMineQueryResult = NonNullable<Awaited<ReturnType<typeof venuesControllerFindMine>>>
export type VenuesControllerFindMineQueryError = unknown


export function useVenuesControllerFindMine<TData = Awaited<ReturnType<typeof venuesControllerFindMine>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof venuesControllerFindMine>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof venuesControllerFindMine>>,
          TError,
          Awaited<ReturnType<typeof venuesControllerFindMine>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useVenuesControllerFindMine<TData = Awaited<ReturnType<typeof venuesControllerFindMine>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof venuesControllerFindMine>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof venuesControllerFindMine>>,
          TError,
          Awaited<ReturnType<typeof venuesControllerFindMine>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useVenuesControllerFindMine<TData = Awaited<ReturnType<typeof venuesControllerFindMine>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof venuesControllerFindMine>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useVenuesControllerFindMine<TData = Awaited<ReturnType<typeof venuesControllerFindMine>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof venuesControllerFindMine>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getVenuesControllerFindMineQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const venuesControllerFindOne = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<VenueDto>(
      {url: `/api/venues/${id}`, method: 'GET', signal
    },
      );
    }




export const getVenuesControllerFindOneQueryKey = (id: string,) => {
    return [
    `/api/venues/${id}`
    ] as const;
    }


export const getVenuesControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof venuesControllerFindOne>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof venuesControllerFindOne>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getVenuesControllerFindOneQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof venuesControllerFindOne>>> = ({ signal }) => venuesControllerFindOne(id, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof venuesControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type VenuesControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof venuesControllerFindOne>>>
export type VenuesControllerFindOneQueryError = unknown


export function useVenuesControllerFindOne<TData = Awaited<ReturnType<typeof venuesControllerFindOne>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof venuesControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof venuesControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof venuesControllerFindOne>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useVenuesControllerFindOne<TData = Awaited<ReturnType<typeof venuesControllerFindOne>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof venuesControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof venuesControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof venuesControllerFindOne>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useVenuesControllerFindOne<TData = Awaited<ReturnType<typeof venuesControllerFindOne>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof venuesControllerFindOne>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useVenuesControllerFindOne<TData = Awaited<ReturnType<typeof venuesControllerFindOne>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof venuesControllerFindOne>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getVenuesControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const venuesControllerUpdate = (
    id: string,
    updateVenueDto: UpdateVenueDto,
 signal?: AbortSignal
) => {


      return customInstance<VenueDto>(
      {url: `/api/venues/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateVenueDto, signal
    },
      );
    }




export const getVenuesControllerUpdateMutationKey = () => ['venuesControllerUpdate'] as const;

export const getVenuesControllerUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof venuesControllerUpdate>>, TError,VenuesControllerUpdateMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof venuesControllerUpdate>>, TError,VenuesControllerUpdateMutationVariables, TContext> => {

const mutationKey = getVenuesControllerUpdateMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof venuesControllerUpdate>>, VenuesControllerUpdateMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  venuesControllerUpdate(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type VenuesControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof venuesControllerUpdate>>>
    export type VenuesControllerUpdateMutationBody = UpdateVenueDto
    export type VenuesControllerUpdateMutationError = unknown
    export type VenuesControllerUpdateMutationVariables = {id: string;data: UpdateVenueDto}

    export const useVenuesControllerUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof venuesControllerUpdate>>, TError,VenuesControllerUpdateMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof venuesControllerUpdate>>,
        TError,
        VenuesControllerUpdateMutationVariables,
        TContext
      > => {
      return useMutation(getVenuesControllerUpdateMutationOptions(options), queryClient);
    }
